voice_samples:
  binh_nam_bac:
    name: "Bình (nam miền Bắc)"
    description: "Male voice from Northern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Bình (nam miền Bắc).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Bình (nam miền Bắc).txt"
  
  doan_nu_nam:
    name: "Đoan (nữ miền Nam)"
    description: "Female voice from Southern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Đoan (nữ miền Nam).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Đoan (nữ miền Nam).txt"
  
  dung_nu_nam:
    name: "Dung (nữ miền Nam)"
    description: "Female voice from Southern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Dung (nữ miền Nam).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Dung (nữ miền Nam).txt"
  
  huong_nu_bac:
    name: "Hương (nữ miền Bắc)"
    description: "Female voice from Northern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Hương (nữ miền Bắc).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Hương (nữ miền Bắc).txt"
  
  ly_nu_bac:
    name: "Ly (nữ miền Bắc)"
    description: "Female voice from Northern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Ly (nữ miền Bắc).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Ly (nữ miền Bắc).txt"
  
  ngoc_nu_bac:
    name: "Ngọc (nữ miền Bắc)"
    description: "Female voice from Northern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Ngọc (nữ miền Bắc).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Ngọc (nữ miền Bắc).txt"
  
  nguyen_nam_nam:
    name: "Nguyên (nam miền Nam)"
    description: "Male voice from Southern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Nguyên (nam miền Nam).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Nguyên (nam miền Nam).txt"
  
  son_nam_nam:
    name: "Sơn (nam miền Nam)"
    description: "Male voice from Southern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Sơn (nam miền Nam).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Sơn (nam miền Nam).txt"
  
  tuyen_nam_bac:
    name: "Tuyên (nam miền Bắc)"
    description: "Male voice from Northern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Tuyên (nam miền Bắc).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Tuyên (nam miền Bắc).txt"
  
  vinh_nam_nam:
    name: "Vĩnh (nam miền Nam)"
    description: "Male voice from Southern Vietnam"
    audio: "python_api/assets/vieneu-tts-sample/voice/Vĩnh (nam miền Nam).wav"
    text: "python_api/assets/vieneu-tts-sample/voice/Vĩnh (nam miền Nam).txt"

backbone_configs:
  F5-TTS:
    repo: "SWivid/F5-TTS"
  E2-TTS:
    repo: "SWivid/E2-TTS"

codec_configs:
  Vocos:
    repo: "charactr/vocos-mel-24khz"
  BigVGAN:
    repo: "nvidia/bigvgan_v2_24khz_100band_256x"

text_settings:
  max_chars_per_chunk: 256
